# Default values for cryptpad-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas
replicaCount: 1

# -- Enable to choose witch kind of workload will be used: (true) StatefulSet or (false) for Deployment
workloadStateful: true

# Parameters for the Cryptpad image used
image:
  pullPolicy: IfNotPresent
  repository: cryptpad/cryptpad
  tag: "version-5.4.0"
  # repository: git.xwikisas.com:5050/xwiki-cloud-infrastructure/docker-images/cryptpad
  # tag: "latest"

# -- Configuration of the [application](https://docs.cryptpad.org/en/admin_guide/customization.html#application-config)
application_config:
  # Check all the configurable values: https://github.com/xwiki-labs/cryptpad/blob/main/www/common/application_config_internal.js
  # availableLanguages: [ 'en', 'fr', 'de' ]
  # privacy: |
  #  {
  #    "default": 'https://example.com/privacy.html',
  #    "en": 'https://example.com/privacy.en.html', // in case English is not your default language
  #    "fr": 'https://example.com/privacy.fr.html', // another language
  #    "de": 'https://example.com/privacy.de.html', // you get the idea?
  #  }

# -- File to mount for the CPAD Configuration (`CPAD_CONF`)
cpadConfig: "/cryptpad/config/config.js"

# https://docs.cryptpad.org/en/admin_guide/installation.html#admin-cryptpad-config
# [Configuration of Cryptpad](https://docs.cryptpad.org/en/admin_guide/installation.html#admin-cryptpad-config)
config:
  #########################
  # NETWORK CONFIGURATION #
  #########################
  # -- httpAddress specifies the address on which the nodejs server should be accessible.
  httpAddress: '0.0.0.0'

  ####################
  # Database Volumes #
  ####################
  # -- Directory where files/documents should be stored. 
  filePath: './datastore/'
  # -- Directory to archive data for a configurable period before deleting it. 
  archivePath: './data/archive'
  # -- Directory to store documents that was pinned to to be stored by the server indefinitely. 
  pinPath: './data/pins'
  # -- Directory to store a list of scheduled tasks. 
  taskPath: './data/tasks'
  # -- Directory to store authenticated blocks. 
  blockPath: './block'
  # -- Directory to store encrypted files that was uploaded. 
  blobPath: './blob'
  # -- Directory to store incomplete blobs in a 'staging' area until they are fully uploaded. 
  blobStagingPath: './data/blobstage'
  # -- TODO
  decreePath: './data/decrees'
  # -- Directory to store logging events. 
  logPath: './data/logs'

  #############
  # Debugging #
  #############
  # -- Enable verbose logging
  verbose: false
  # -- Log activity to stdout, this may be useful for debugging
  logToStdout: false
  # -- Change log level from this list below by order of importance: (silly, verbose, debug, feedback, info, warn, error). 
  logLevel: 'info'
  # -- Enable feedback log, but requires feedback on log level to work. 
  logFeedback: false

  # Surplus information
  installMethod: 'helm-docker'

  # Administrator keys
  # https://docs.cryptpad.org/en/admin_guide/installation.html#configure-administrators
  # -- Public signing key of users to give admin panel access
  adminKeys: []
  # adminKeys: [
  #   "[cryptpad-user1@my.awesome.website/YZgXQxKR0Rcb6r6CmxHPdAGLVludrAF2lEnkbx1vVOo=]",
  # ]

# -- Allow documents and media be embedded on other websites. This will add an "Embed" option on the Share menu. 
enableEmbedding: false 

# TODO: remove 
# Check values on https://github.com/xwiki-labs/cryptpad-docker#environment-variables
# For CPAD_MAIN_DOMAIN and CPAD_SANDBOX_DOMAIN values httpUnsafeOrigin and httpSafeOrigin will be used.
# CryptPad API subdomain FQDN
# @ignore
apiDomain: ""
# CryptPad files subdomain FQDN
# @ignore
filesDomain: ""
# Trusted proxy address or CIDR
# @ignore
trustedProxy: ""
# Header to get client IP from (`X-Real-IP` or `X-Forwarded-For`)
# @ignore
realIpHeader: ""
# Instruct Nginx to perform a recursive search to find client's real IP (`on`/`off`) (see [ngx_http_realip_module](https://nginx.org/en/docs/http/ngx_http_realip_module.html))
# @ignore
realIpRecursive: ""
# Path to TLS certificate file
# @ignore
tlsCert: ""
# Path to TLS private key file
# @ignore
tlsKey: ""
# Path to Diffie-Hellman parameters file
# @ignore
tlsDhParam: ""
# Disable HTTP2
# @ignore
http2Disable: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for the Pod
podAnnotations: {}

# -- Security context for the Pod
podSecurityContext:
  fsGroup: 4001

# -- Security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Values for the service
service:
  portName: node
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: http
  # Set an array of externalIPs for the service
  externalIPs: []
    # - 10.20.30.40
    # - 10.20.30.41
  # Reference: https://kubernetes.io/docs/reference/networking/virtual-ips/#session-affinity
  sessionAffinity: ClientIP

# Values for the ingress
ingress:
  # Enable the ingress
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: secret-tls

# -- Specify default resources.
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube.
resources: {}
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 200m
  #   memory: 1024Mi
  # requests:
  #   cpu: 200m
  #   memory: 1024Mi

autoscaling:
  # -- Enable the Autoscaling
  enabled: false
  # -- Minimal numbers of replicas
  minReplicas: 1
  # -- Maximum numbers of replicas
  maxReplicas: 100
  # -- Percentage of the targeted CPU Utilization
  targetCPUUtilizationPercentage: 80
  # -- Percentage of the targeted Memory Utilization
  targetMemoryUtilizationPercentage: 80

# -- Values for the Node Selector
nodeSelector: {}

# -- Values for the Tolerations
tolerations: []

# -- Values for the Affinity
affinity: {}

persistence:
  # -- Enable the persistence
  enabled: true
  cryptpad:
    blob:
      existingClaim: ""
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: "100Mi"
      annotations: {}
      labels: {}
      selector: {}
      dataSource: {}
    block:
      existingClaim: ""
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: "100Mi"
      annotations: {}
      labels: {}
      selector: {}
      dataSource: {}
    data:
      existingClaim: ""
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: "100Mi"
      annotations: {}
      labels: {}
      selector: {}
      dataSource: {}
    datastore:
      existingClaim: ""
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: "100Mi"
      annotations: {}
      labels: {}
      selector: {}
      dataSource: {}

