apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptpad-helm.fullname" . }}
  labels:
    {{- include "cryptpad-helm.labels" . | nindent 4 }}
data:
  config.js: |
    /* globals module */

    module.exports = {
          {{- if .Values.config.httpUnsafeOrigin }}  
            httpUnsafeOrigin: {{ .Values.config.httpUnsafeOrigin }}, 
          {{- else if .Values.ingress.enabled }}
            httpUnsafeOrigin: 'https://{{ (index .Values.ingress.hosts 0).host }}',
          {{- else }}
            httpUnsafeOrigin: 'http://localhost:3000',
          {{- end}}
       
          {{- if .Values.config.httpSafeOrigin }}  
            httpSafeOrigin: {{ .Values.config.httpSafeOrigin }}, 
          {{- else if .Values.ingress.enabled }}
            httpSafeOrigin: 'https://{{ (index .Values.ingress.hosts 0).host }}',
          {{- else }}
            httpSafeOrigin: 'http://localhost:3000',
          {{- end}}

            adminKeys: [
              {{- range $key := .Values.adminKeys }}
                {{ $key | quote }}, 
              {{- end }}
            ], 

          {{- range $key, $value := .Values.config }}
            {{ $key }}:  {{ $value | quote }}, 
          {{- end }}

        };