name: Generate Helm documentation

on: 
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'charts/**'

permissions:
  contents: write

jobs:
  update-chart-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gabe565/setup-helm-docs-action@v1
      - run: helm-docs
      - name: Commit documentation
        run: |
          git config --global user.name 'GridexX'
          git config --global user.email 'gridexx@users.noreply.github.com'
          git add .
          git commit -sm "docs: generate chart documentation"
          git push